### ISSUE TITLE
bithomp api returns wrong list in fetching nft lists

### ISSUE THREAD

**Issue by AtosDev** [Bithomp/xrpl-api#53]
- in first fetch
https://bithomp.com/api/cors/v2/nfts?list=nfts&issuer=rTESTADDRESSTESTADDRESS&taxon=123
it returns the nft list from 1 to 100
- in second fetch with marker
https://bithomp.com/api/cors/v2/nfts?list=nfts&issuer=rTESTADDRESSTESTADDRESS&taxon=123&marker=10101010101
it returns the nft list from 102 to ...
- so it's missing the 101th nft in the list

it's same on bithomp explorer as well.
so I can't see the 101th nft

**Comment by ildaruz** [comment]
Thanks for informing. Could you take a look and check if it works correct for you now?

**Comment by AtosDev** [comment]
sure, it works well currently.
It's not a big problem in development but it's not small for users.

Best Regards.
Toba
