### ISSUE TITLE
issue while installing npm package 

### ISSUE THREAD

**Issue by jonathanlei** [Bithomp/xrpl-api#54]
While following the instructions in README, I can't install the npm package as I need authentication token
<img width="1201" alt="Screenshot 2023-06-20 at 1 43 46 PM" src="https://github.com/Bithomp/xrpl-api/assets/9340787/ed718b11-6d29-4878-b9d5-cbed5123275b">

**Comment by intelliot** [comment]
For future reference: GitHub Packages requires an authentication token, even just to read public packages. See https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry

**Comment by ildaruz** [comment]
I've moved deploy to npm repo
https://www.npmjs.com/package/@bithomp/xrpl-api
