### ISSUE TITLE
Validator list requirement 

### ISSUE THREAD

**Issue by jonathanlei** [Bithomp/xrpl-api#55]
in the process of reviewing the validator tool - 
when I pass in the example validator in the example code - 
`  const validators = ["nHBidG3pZK11zQD6kpNDoAhDxH6WLGui6ZxSbUx7LSqLHsgzMPec"];`
it would generate a validator list for me
but when I put in one of the validator public keys from vl.ripple.com 
 const validators = ["ED13AAFCB6A87BCB5D093C2EF37F04431C291126D674293305152D9776C6ABA4D6"];
I get an error 
`node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "invalidParams".] {
  code: 'ERR_UNHANDLED_REJECTION'
}`
is it because I didn't put the signing key and only provided public key? 
could you add more documentation on what kind of validator keys we need?

**Comment by ildaruz** [comment]
Validator public key always starts with letter `n`. Here is en example of such list of validators for mainnet
https://bithomp.com/validators


In your example  the keys `ED..` is a public ed25519 key in hex format, such key can be converted to validator public key with `ripple-address-codec`  by `encodeNodePublic` function, here is an example https://github.com/Bithomp/xrpl-api/blob/master/src/validator.ts#L69

**Comment by jonathanlei** [comment]
thanks for the clarification - I was able to get the validator and signing secrets working. 
Would you mind adding some additional documentation to explain the format needed to create a VL? I imagine other developers would have confusions about this beyond just me
