### ISSUE TITLE
Add support to Validator List v2

### ISSUE THREAD

**Issue by jonathanlei** [Bithomp/xrpl-api#60]
Hi Bithomp team, 
I am writing this message to ask for support on generating UNL v2 with the bithomp API. The specific spec has been made public via https://github.com/XRPLF/XRPL-Standards/pull/124. 
The main changes in this spec is adding a future effective date to UNLs so that all nodes in the peer network can switch to a new UNL simultaneously, and the change was merged to rippled in 2021. 

Here's a quick overview of what's needed:
Support for UNL v2 Format: Compliant with the new spec.
Integration with Existing Code: Working with the current setup, e.g., using` BithompXRPL.Client.createVL`.

Community developers like us rely heavily on Bithomp's tools, and this enhancement will significantly improve our ability to create and maintain validator lists.
Thanks!

**Comment by ildaruz** [comment]
Thanks for contacting, I will implement version 2 soon.

**Comment by ildaruz** [comment]
You can try to use `BithompXRPL.Client.createVLv2`
example:
https://github.com/Bithomp/xrpl-api/blob/master/README.md#create-validator-list-version-2

Let me know if something is not correct

**Comment by jonathanlei** [comment]
is this updated with npm?

**Comment by ildaruz** [comment]
@jonathanlei yep, it was released with version 2.5.0
